[colors.primary]
foreground = "#96a8a8"
background = "#161c1c"

[colors.cursor]
text = "#0000ff"
cursor = "#ff0000"

[colors.selection]
text = "#cdcecf"
background = "#2b3b51"

[colors.normal]
black = "#5d5d5d"
red = "#a88985"
green = "#92a896"
yellow = "#a8a891"
blue = "#81a0a6"
magenta = "#8b96a8"
cyan = "#96a8a8"
white = "#7b7b7b"

[colors.bright]
black = "#5d5d5d"
red = "#a88985"
green = "#92a896"
yellow = "#a8a891"
blue = "#81a0a6"
magenta = "#8b96a8"
cyan = "#96a8a8"
white = "#7b7b7b"
