[colors.primary]
foreground = "#94a6a6"
background = "#171d1d"

[colors.cursor]
text = "#0000ff"
cursor = "#ff0000"

[colors.selection]
text = "#cdcecf"
background = "#2b3b51"

[colors.normal]
black = "#5d5d5d"
red = "#9f7f7b"
green = "#8ea492"
yellow = "#a4a48b"
blue = "#7691a2"
magenta = "#8792a4"
cyan = "#94a6a6"
white = "#7b7b7b"

[colors.bright]
black = "#5d5d5d"
red = "#9f7f7b"
green = "#8ea492"
yellow = "#a4a48b"
blue = "#7691a2"
magenta = "#8792a4"
cyan = "#94a6a6"
white = "#7b7b7b"
